### ISSUE TITLE
What could possibly go wrong here? And what  should you do instead?

### ISSUE THREAD

**Issue by changetocoding** [Xietyz/Misc#9]
https://github.com/Xietyz/Misc/blob/9176d88a50d37e8798c695d2c1d49e3305643b0a/StrategyConsole/WebAPI/Controllers/CsvPnlController.cs#L38

**Comment by Xietyz** [comment]
i can't find that line. i probably changed it somewhere down the line. hopefully.
EDIT:
Nevermind, Jacob fixed it a while ago, forgot to update it.
